version: "3.9"
services:
  db:
    image: postgres:15
    container_name: auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
